export const AUTH = {
  SUCCESS: "AUTH_SUCCESS",
  LOGOUT: "LOG_OUT",
};

export const DB = {
  GET_ALL_RECIPES: "GET_ALL",
  GET_ALL_INGREDIENTS: "GET_ALL_INGREDIENTS",
  GET_RECIPE_BY_ID: "GET_BY_ID",
  REMOVE_BY_ID: "REMOVE_BY_ID",
};
